/** ai.js: it involves graph search algorithms. */

import { isGoal } from './state.js';
import { getValidMoves, applyMove } from './game.js';

/**
 * Heuristic 1: Misplaced Tiles
 * Counts how many tiles (ignoring 0) are not in the goal state position.
 */
export function getMisplacedTilesCount(state, goalState) {
    let count = 0;
    for (let i = 0; i < 9; i++) {
        if (state[i] !== 0 && state[i] !== goalState[i]) {
            count++;
        }
    }
    return count;
}

/**
 * Heuristic 2: Manhattan Distance
 * Sum of the vertical and horizontal distance of each tile to its target position.
 */
export function getManhattanDistance(state, goalState) {
    let distance = 0;
    for (let i = 0; i < 9; i++) {
        const tile = state[i];
        if (tile !== 0) {
            const goalIndex = goalState.indexOf(tile);  // Find where this token should be in the goalState

            // Current coordinates
            const currentRow = Math.floor(i / 3);
            const currentCol = i % 3;

            // Target coordinates
            const goalRow = Math.floor(goalIndex / 3);
            const goalCol = goalIndex % 3;

            distance += Math.abs(currentRow - goalRow) + Math.abs(currentCol - goalCol);
        }
    }
    return distance;
}

/** Auxiliary class for the search tree nodes. */
class Node {
    constructor(state, parent, move, g, h) {
        this.state = state;
        this.parent = parent; // Previous node (to reconstruct the path)
        this.move = move;     // Move generated by this node (up, down, left, right)
        this.g = g;           // Cost from the start (depth)
        this.h = h;           // Estimated heuristic cost to the end
        this.f = g + h;
    }
}

/**

 * Unified main search function (BFS and A*).
 *
 * @param {number[]} initialState
 * @param {number[]} goalState
 * @param {string} difficulty - 'easy' (Misplaced), 'normal', or 'hard' (Manhattan)
 * @returns {string[]} Array of moves to solve the puzzle, e.g., ['up', 'left', 'down']
 */
export function solvePuzzle(initialState, goalState, difficulty) {
    if (isGoal(initialState, goalState)) return [];

    const openList = [];  // OpenList: Nodes to explore (priority queue)
    const closedSet = new Set();  // Set of visited to avoid infinite loops (we store the state as a string)

    const startNode = new Node(initialState, null, null, 0, 0);
    openList.push(startNode);

    let nodesExplored = 0;

    while (openList.length > 0) {
        // 1. Extract the node with the smallest f(n).
        openList.sort((a, b) => a.f - b.f);
        const currentNode = openList.shift();

        const stateString = currentNode.state.toString();
        if (closedSet.has(stateString)) continue;

        closedSet.add(stateString);
        nodesExplored++;

        // 2. Did we reach the goal?
        if (isGoal(currentNode.state, goalState)) {
            console.log(`Solved! Nodes explored: ${nodesExplored}, Depth: ${currentNode.g}`);
            return reconstructPath(currentNode);
        }

        // 3. Expand neighbors (Generate children)
        const validMoves = getValidMoves(currentNode.state);

        for (const move of validMoves) {
            const nextState = applyMove(currentNode.state, move);
            const nextStateString = nextState.toString();

            if (!closedSet.has(nextStateString)) {
                const g = currentNode.g + 1;  // Calculate g (step-by-step cost is always 1 in an 8-puzzle)

                // Calculate h according to the difficulty (AI Strategy)
                let h = 0;
                if (difficulty === 'easy') {
                    h = getMisplacedTilesCount(nextState, goalState);
                } else {
                    h = getManhattanDistance(nextState, goalState);
                }

                const childNode = new Node(nextState, currentNode, move, g, h);
                openList.push(childNode);
            }
        }
    }

    return null;  // If the queue empties and there is no solution (it shouldn't happen...)
}

/**
 * Reconstructs the list of moves from the final node backwards.
 */
function reconstructPath(node) {
    const path = [];
    let current = node;
    while (current.parent !== null) {
        path.push(current.move);
        current = current.parent;
    }
    return path.reverse();
}
